### ISSUE TITLE
[Bug]: ./app Error

### ISSUE THREAD

**Issue by TypTech** [crocofied/CoreControl#87]
### What happened?

For 40 minutes, I tried to install the CoreControl application and kept getting the same error.

### Steps to reproduce

Here is my error:

root@CoreControl:~/CoreControl# docker-compose up -d
Creating volume "corecontrol_postgres_data" with default driver
Recreating corecontrol_db_1 ... done
Creating corecontrol_web_1  ... done
Creating corecontrol_agent_1 ... error

ERROR: for corecontrol_agent_1  Cannot start service agent: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./app": stat ./app: permission denied: unknown

ERROR: for agent  Cannot start service agent: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./app": stat ./app: permission denied: unknown
ERROR: Encountered errors while bringing up the project.
root@CoreControl:~/CoreControl#

### Operating System

Debian 12

### Version

1.0.1

**Comment by gide0n** [comment]
The same case here.

**Comment by nocci-sl** [comment]
can confirm - used this from the git:

```
services:
  web:
    image: haedlessdev/corecontrol:latest
    ports:
      - 2222:3000
    environment:
      JWT_SECRET: MY_VERY_RANDOM_SECRET # Replace with a secure random string
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres

  agent:
    image: haedlessdev/corecontrol-agent:latest
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 2s
      timeout: 2s
      retries: 10
volumes:
  postgres_data: null
networks: {}
```
