### ISSUE TITLE
Executed on a docker swarm

### ISSUE THREAD

**Issue by xxcbzxx** [crocofied/CoreControl#9]
> next start

   ▲ Next.js 15.3.0

   - Local:        http://localhost:3000

   - Network:      http://10.0.0.132:3000

> corecontrol@0.1.0 start

 ✓ Starting...


> next start

   ▲ Next.js 15.3.0

   - Local:        http://localhost:3000

[Error: Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id]

   - Network:      http://10.0.0.129:3000

 ✓ Starting...

[Error: Could not find a production build in the '.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id]

----
Using portainer and docker swarm to deploy the following yml - getting mixed answers from ChatGPT... - saying i could install npm or build it with the next build on the docker file.

-------------------

services:
  web:
    image: haedlessdev/corecontrol:latest
    ports:
      - "3000:3000"
    environment:
      LOGIN_EMAIL: "email@email.com"
      LOGIN_PASSWORD: "SECRET_PASSWORD"
      JWT_SECRET: "SECRET_PASSWORD"
      ACCOUNT_SECRET: "SECRET_PASSWORD"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?sslmode=require&schema=public"
    depends_on:
      - db
      - agent
    networks:
      - core_net

  agent:
    image: haedlessdev/corecontrol-agent:latest
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?sslmode=require&schema=public"
    networks:
      - core_net

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /mnt/cephfs/corecontrol/postgres_data:/var/lib/postgresql/data
    networks:       
      - core_net

networks:
  core_net:
    driver: overlay

**Comment by kuartelgeneral** [comment]
I have the same error with Portainer CE 2.273 LTS. My compose file is:

```
services:
  web:
    image: haedlessdev/corecontrol:latest
    ports:
      - "3700:3000"
    environment:
      LOGIN_EMAIL: "email@email.com"
      LOGIN_PASSWORD: "password"
      JWT_SECRET: sercet_key
      ACCOUNT_SECRET: secret_key
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?sslmode=require&schema=public"
    depends_on:
      - db
      - agent

  agent:
    image: haedlessdev/corecontrol-agent:latest
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?sslmode=require&schema=public"

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /home/user/docker/corecontrol/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
```
